-- Migration: Insert initial templates
INSERT INTO public.templates (id, name, description, domain, category, is_global, content) VALUES
(gen_random_uuid(), 'Software Engineering Sprint', 'Agile sprint tracking with backlog, in progress, review, and QA.', 'Engineering & IT', 'Agile', true, '{"statuses":[{"name":"Backlog","color":"slate","position":1},{"name":"In Progress","color":"blue","position":2},{"name":"In Review","color":"purple","position":3},{"name":"QA","color":"orange","position":4},{"name":"Done","color":"emerald","position":5}],"tasks":[{"title":"Setup repository","status":"Backlog","priority":"High","position":1},{"title":"Design DB schema","status":"Backlog","priority":"Urgent","position":2},{"title":"Define API endpoints","status":"Backlog","priority":"Normal","position":3}],"taskTypes":["Epic","Story","Bug","Task"]}'),
(gen_random_uuid(), 'IT Helpdesk', 'Ticket tracking and resolution flow.', 'Engineering & IT', 'Support', true, '{"statuses":[{"name":"New","color":"red","position":1},{"name":"Investigating","color":"orange","position":2},{"name":"Waiting on Customer","color":"yellow","position":3},{"name":"Resolved","color":"emerald","position":4}],"tasks":[{"title":"Password reset request","status":"New","priority":"Normal","position":1},{"title":"VPN access issue","status":"New","priority":"High","position":2}],"taskTypes":["Incident","Service Request","Problem","Change"]}'),
(gen_random_uuid(), 'Bug Tracker', 'Issue tracking and resolution.', 'Engineering & IT', 'QA', true, '{"statuses":[{"name":"Triage","color":"slate","position":1},{"name":"To Do","color":"blue","position":2},{"name":"Fixing","color":"purple","position":3},{"name":"Testing","color":"orange","position":4},{"name":"Resolved","color":"emerald","position":5}],"tasks":[{"title":"Fix login screen overflow on mobile","status":"Triage","priority":"High","position":1},{"title":"Memory leak in data table","status":"Triage","priority":"Urgent","position":2}],"taskTypes":["Bug","Regression","Enhancement"]}'),
(gen_random_uuid(), 'Security Audit', 'Compliance checks and security reviews.', 'Engineering & IT', 'Security', true, '{"statuses":[{"name":"Pending","color":"slate","position":1},{"name":"Auditing","color":"blue","position":2},{"name":"Remediation","color":"orange","position":3},{"name":"Compliant","color":"emerald","position":4}],"tasks":[{"title":"Review IAM roles","status":"Pending","priority":"High","position":1},{"title":"Rotate production database keys","status":"Pending","priority":"Urgent","position":2}],"taskTypes":["Vulnerability","Risk","Task"]}'),
(gen_random_uuid(), 'Website Redesign', 'Page updates, design, and deployment.', 'Engineering & IT', 'Web', true, '{"statuses":[{"name":"Wireframes","color":"slate","position":1},{"name":"Design","color":"blue","position":2},{"name":"Development","color":"purple","position":3},{"name":"QA","color":"orange","position":4},{"name":"Live","color":"emerald","position":5}],"tasks":[{"title":"Homepage wireframes","status":"Wireframes","priority":"High","position":1},{"title":"Update global font stack","status":"Wireframes","priority":"Normal","position":2}],"taskTypes":["Page","Component","Task","Bug"]}'),
(gen_random_uuid(), 'Product Roadmap', 'High-level product feature tracking.', 'Product & Design', 'Planning', true, '{"statuses":[{"name":"Idea","color":"slate","position":1},{"name":"Up Next","color":"blue","position":2},{"name":"In Development","color":"orange","position":3},{"name":"Released","color":"emerald","position":4}],"tasks":[{"title":"Implement Dark Mode","status":"Idea","priority":"Normal","position":1},{"title":"SSO Integration","status":"Idea","priority":"High","position":2}],"taskTypes":["Initiative","Feature","Milestone"]}'),
(gen_random_uuid(), 'Design System Updates', 'Managing UI components and design tokens.', 'Product & Design', 'UI/UX', true, '{"statuses":[{"name":"Backlog","color":"slate","position":1},{"name":"Designing","color":"blue","position":2},{"name":"Review","color":"purple","position":3},{"name":"Approved","color":"emerald","position":4}],"tasks":[{"title":"Create new Button variants","status":"Backlog","priority":"Normal","position":1},{"title":"Audit color contrast for accessibility","status":"Backlog","priority":"High","position":2}],"taskTypes":["Component","Token","Audit"]}'),
(gen_random_uuid(), 'User Research', 'Interviews, surveys, and usability testing.', 'Product & Design', 'Research', true, '{"statuses":[{"name":"Recruiting","color":"slate","position":1},{"name":"Interviewing","color":"blue","position":2},{"name":"Synthesizing","color":"purple","position":3},{"name":"Done","color":"emerald","position":4}],"tasks":[{"title":"Draft survey questions for V2","status":"Recruiting","priority":"Normal","position":1},{"title":"Schedule 5 user interviews","status":"Recruiting","priority":"High","position":2}],"taskTypes":["Interview","Survey","Analysis"]}'),
(gen_random_uuid(), 'Marketing Campaign', 'Track campaigns from concept to launch.', 'Marketing & Sales', 'Campaigns', true, '{"statuses":[{"name":"Planning","color":"slate","position":1},{"name":"Drafting","color":"blue","position":2},{"name":"Review","color":"purple","position":3},{"name":"Published","color":"emerald","position":4}],"tasks":[{"title":"Define Q3 campaign goals","status":"Planning","priority":"High","position":1},{"title":"Draft landing page copy","status":"Planning","priority":"Normal","position":2}],"taskTypes":["Campaign","Asset","Task"]}'),
(gen_random_uuid(), 'Sales Pipeline', 'Lead generation and deal tracking.', 'Marketing & Sales', 'CRM', true, '{"statuses":[{"name":"Lead","color":"slate","position":1},{"name":"Contacted","color":"blue","position":2},{"name":"Proposal","color":"purple","position":3},{"name":"Closed Won","color":"emerald","position":4},{"name":"Closed Lost","color":"red","position":5}],"tasks":[{"title":"Acme Corp - Initial Outreach","status":"Lead","priority":"Normal","position":1},{"title":"Stark Industries - Follow up","status":"Lead","priority":"High","position":2}],"taskTypes":["Lead","Deal","Account"]}'),
(gen_random_uuid(), 'Content Calendar', 'Blog and social media content planning.', 'Marketing & Sales', 'Content', true, '{"statuses":[{"name":"Idea","color":"slate","position":1},{"name":"Writing","color":"blue","position":2},{"name":"Editing","color":"purple","position":3},{"name":"Scheduled","color":"orange","position":4},{"name":"Published","color":"emerald","position":5}],"tasks":[{"title":"Top 10 tips for remote work blog post","status":"Idea","priority":"Normal","position":1},{"title":"Product update newsletter","status":"Idea","priority":"High","position":2}],"taskTypes":["Blog Post","Social Media","Video","Newsletter"]}'),
(gen_random_uuid(), 'Social Media Strategy', 'Campaigns, posts, and analytics.', 'Marketing & Sales', 'Social', true, '{"statuses":[{"name":"Idea","color":"slate","position":1},{"name":"Creating","color":"blue","position":2},{"name":"Review","color":"purple","position":3},{"name":"Scheduled","color":"orange","position":4},{"name":"Posted","color":"emerald","position":5}],"tasks":[{"title":"Draft launch tweets","status":"Idea","priority":"High","position":1},{"title":"Create instagram reel for new feature","status":"Idea","priority":"Normal","position":2}],"taskTypes":["Post","Reel","Story"]}'),
(gen_random_uuid(), 'Brand Launch', 'Assets, PR, and launch logistics.', 'Marketing & Sales', 'Brand', true, '{"statuses":[{"name":"Strategy","color":"slate","position":1},{"name":"Creative","color":"blue","position":2},{"name":"Approvals","color":"orange","position":3},{"name":"Launched","color":"emerald","position":4}],"tasks":[{"title":"Finalize brand guidelines","status":"Strategy","priority":"Urgent","position":1},{"title":"Order new swag inventory","status":"Strategy","priority":"Normal","position":2}],"taskTypes":["Asset","Press Release","Event"]}'),
(gen_random_uuid(), 'Budget Planning', 'Financial forecasting and budgeting.', 'Operations & Finance', 'Planning', true, '{"statuses":[{"name":"Drafting","color":"slate","position":1},{"name":"Under Review","color":"orange","position":2},{"name":"Approved","color":"emerald","position":3}],"tasks":[{"title":"Draft Q4 marketing budget","status":"Drafting","priority":"High","position":1},{"title":"Review software subscriptions","status":"Drafting","priority":"Normal","position":2}],"taskTypes":["Budget","Forecast","Expense"]}'),
(gen_random_uuid(), 'Event Planning', 'Logistics for virtual and in-person events.', 'Operations & Finance', 'Events', true, '{"statuses":[{"name":"Planning","color":"slate","position":1},{"name":"Preparation","color":"blue","position":2},{"name":"Execution","color":"purple","position":3},{"name":"Wrap-up","color":"emerald","position":4}],"tasks":[{"title":"Book venue for annual retreat","status":"Planning","priority":"Urgent","position":1},{"title":"Send save-the-date emails","status":"Planning","priority":"Normal","position":2}],"taskTypes":["Logistics","Vendor","Attendee"]}'),
(gen_random_uuid(), 'Facilities Maintenance', 'Office repairs and requests.', 'Operations & Finance', 'Facilities', true, '{"statuses":[{"name":"Reported","color":"red","position":1},{"name":"Assigned","color":"blue","position":2},{"name":"In Progress","color":"orange","position":3},{"name":"Completed","color":"emerald","position":4}],"tasks":[{"title":"Fix broken AC in conference room","status":"Reported","priority":"Urgent","position":1},{"title":"Order more coffee pods","status":"Reported","priority":"Low","position":2}],"taskTypes":["Repair","Supply Request","Inspection"]}'),
(gen_random_uuid(), 'Procurement', 'Purchasing and vendor management.', 'Operations & Finance', 'Procurement', true, '{"statuses":[{"name":"Request","color":"slate","position":1},{"name":"Quoting","color":"blue","position":2},{"name":"Approval","color":"orange","position":3},{"name":"Purchased","color":"emerald","position":4},{"name":"Received","color":"purple","position":5}],"tasks":[{"title":"Request 10 new developer laptops","status":"Request","priority":"High","position":1},{"title":"Renew Slack enterprise license","status":"Request","priority":"Urgent","position":2}],"taskTypes":["Purchase Order","Vendor Evaluation","Invoice"]}'),
(gen_random_uuid(), 'Board Meeting Prep', 'Agenda, slides, and financials.', 'Operations & Finance', 'Meetings', true, '{"statuses":[{"name":"Drafting","color":"slate","position":1},{"name":"Review","color":"orange","position":2},{"name":"Finalized","color":"emerald","position":3}],"tasks":[{"title":"Compile Q2 financial reports","status":"Drafting","priority":"Urgent","position":1},{"title":"Draft CEO presentation","status":"Drafting","priority":"High","position":2}],"taskTypes":["Report","Presentation","Agenda Item"]}'),
(gen_random_uuid(), 'Employee Onboarding', 'Structured onboarding process for new hires.', 'HR & Legal', 'Onboarding', true, '{"statuses":[{"name":"Pre-boarding","color":"slate","position":1},{"name":"Day 1","color":"blue","position":2},{"name":"Week 1","color":"purple","position":3},{"name":"Completed","color":"emerald","position":4}],"tasks":[{"title":"Send welcome email and laptop","status":"Pre-boarding","priority":"High","position":1},{"title":"Schedule HR intro meeting","status":"Pre-boarding","priority":"Normal","position":2}],"taskTypes":["Checklist Item","Meeting","Document"]}'),
(gen_random_uuid(), 'Legal Contract Review', 'Contract generation, review, and signing.', 'HR & Legal', 'Contracts', true, '{"statuses":[{"name":"Draft","color":"slate","position":1},{"name":"Review","color":"orange","position":2},{"name":"Pending Signature","color":"blue","position":3},{"name":"Signed","color":"emerald","position":4}],"tasks":[{"title":"Draft NDA for Acme Corp","status":"Draft","priority":"High","position":1},{"title":"Review vendor agreement for AWS","status":"Review","priority":"Urgent","position":2}],"taskTypes":["Contract","NDA","Compliance Check"]}');

